---
openapi: 3.1.0
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts":
    get:
      summary: list posts
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/posts"
    post:
      summary: create post
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    attributes:
                      title:
                        type: string
                      content:
                        type: string
                      user_id:
                        type: string
  "/api/v1/posts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show post
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/post"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    posts:
      type: object
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/post"
    post:
      type: object
      properties:
        id:
          type: integer
          example: 123
        type:
          type: string
          example: posts
          nullable: true
        attributes:
          type: object
          properties:
            title:
              type: string
              example: Post 1
